### ISSUE TITLE
Errors with new certbot docker image

### ISSUE THREAD

**Issue by raph-isvtec** [vanonox/certbot-dns-scaleway#2]
Seems to happen after a bump from 1.29 to 2.0 in the docker official image (https://hub.docker.com/r/certbot/certbot/):

My Dockerfile:
```
FROM certbot/certbot
RUN pip install certbot-dns-scaleway
```

> $ docker run --rm certbot/certbot --version
> certbot 2.0.0
> 

> $ docker run --rm certbot/with-scaleway --version
> An unexpected error occurred:
> ModuleNotFoundError: No module named 'zope'
> 

After adding "RUN pip install zope.interface" in the dockerfile, a new error is popping:

> $ docker run --rm certbot/with-scaleway --version
> An unexpected error occurred:
> AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
> 

I'm not sure  I can fix this myself :(
Thanks for your time and help !

**Comment by vanonox** [comment]
hi , i will check that asap

**Comment by vanonox** [comment]
it is fixed

**Comment by raph-isvtec** [comment]
Just tested, works perfectly !
Thank you very much :)
